# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: '$(Configuration)'

steps:
- bash: |
    echo "##vso[task.setvariable variable=CommithHash]$(git log --pretty=format:'%h' -n 1)"
- script: mkdir $ARTIFACTSFOLDER

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.101'

- script: dotnet publish -c $CONFIGURATION -r linux-x64
  displayName: 'build linux-x64'

- script: dotnet publish -c $CONFIGURATION -r osx-x64
  displayName: 'build osx-x64'

- script: dotnet publish -c $CONFIGURATION -r win-x64
  displayName: 'build win-x64'

- bash: |
    tar -cvzf $ARTIFACTSFOLDER/spectabis-linux-$(CommitHash).tar.gz src/SpectabisNext/bin/Release/$SDKRELEASEFOLDER/linux-x64

- bash: |
    tar -cvzf $ARTIFACTSFOLDER/spectabis-osx-$(CommitHash).tar.gz src/SpectabisNext/bin/Release/$SDKRELEASEFOLDER/osx-x64

- bash: |
    tar -cvzf $ARTIFACTSFOLDER/spectabis-next-win-$(CommitHash).tar.gz src/SpectabisNext/bin/Release/$SDKRELEASEFOLDER/win-x64

- publish: $(System.DefaultWorkingDirectory)/$(ArtifactsFolder)