trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/SpectabisService
    - src/SpectabisLib

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: '$(Configuration)'

steps:
- script: mkdir $(ARTIFACTSFOLDER)

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.101'

- script: dotnet publish src/SpectabisService -c $(CONFIGURATION) -r linux-x64 -o $(ServiceArtifact)
  displayName: 'Build Service Package'
  
- script: dotnet publish Tests/ServiceTests -c $(CONFIGURATION) -r linux-x64 -o $(TestsArtifact)
  displayName: 'Build Tests'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(ServiceArtifact)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-service.zip'
    replaceExistingArchive: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(TestsArtifact)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-tests.zip'
    replaceExistingArchive: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-service.zip'
    artifact: 'Spectabis-Service'
    publishLocation: 'pipeline'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-tests.zip'
    artifact: 'Service-Tests'
    publishLocation: 'pipeline'