trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: '$(Configuration)'

steps:
- bash: |
    echo "##vso[task.setvariable variable=CommithHash]$(git log --pretty=format:'%h' -n 1)"
- script: mkdir $ARTIFACTSFOLDER

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.101'

- script: dotnet publish -c $CONFIGURATION -r linux-x64
  displayName: 'build linux-x64'

- script: dotnet publish -c $CONFIGURATION -r osx-x64
  displayName: 'build osx-x64'

- script: dotnet publish -c $CONFIGURATION -r win-x64
  displayName: 'build win-x64'

- bash: |
    tar -cvzf $ARTIFACTSFOLDER/spectabis-linux-$(Build.SourceVersion).tar.gz src/SpectabisNext/bin/Release/$SDKRELEASEFOLDER/linux-x64/publish

- bash: |
    tar -cvzf $ARTIFACTSFOLDER/spectabis-osx-$(Build.SourceVersion).tar.gz src/SpectabisNext/bin/Release/$SDKRELEASEFOLDER/osx-x64/publish

- bash: |
    tar -cvzf $ARTIFACTSFOLDER/spectabis-win-$(Build.SourceVersion).tar.gz src/SpectabisNext/bin/Release/$SDKRELEASEFOLDER/win-x64/publish

- publish: $(System.DefaultWorkingDirectory)/$(ArtifactsFolder)/spectabis-linux-$(Build.SourceVersion).tar.gz

- publish: $(System.DefaultWorkingDirectory)/$(ArtifactsFolder)/spectabis-osx-$(Build.SourceVersion).tar.gz

- publish: $(System.DefaultWorkingDirectory)/$(ArtifactsFolder)/spectabis-win-$(Build.SourceVersion).tar.gz